development:
  strategy: oauth
  oauth_consumer_key: IJyFpOXj30OBULvSLomHQ
  oauth_consumer_secret: PFYmP1JwM3XmCcixxqSgK9KSwmCzVktfjeiBeASuE
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: IJyFpOXj30OBULvSLomHQ
  oauth_consumer_secret: PFYmP1JwM3XmCcixxqSgK9KSwmCzVktfjeiBeASuE
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: IJyFpOXj30OBULvSLomHQ
  oauth_consumer_secret: PFYmP1JwM3XmCcixxqSgK9KSwmCzVktfjeiBeASuE
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days

